/**
 * Sound Library matcher
 *
 * Maps sfxTags (generated by the LLM) and page content keywords
 * to actual Google Sound Library URLs.
 *
 * The CSV is fetched once and cached in memory.
 * URL: https://d2xsxph8kpxj0f.cloudfront.net/310519663399842622/cuoraNs8SGWCiJUcwSXm4W/google-sound-library_03ad0264.csv
 */

export const SOUND_LIBRARY_CSV_URL =
  "https://d2xsxph8kpxj0f.cloudfront.net/310519663399842622/cuoraNs8SGWCiJUcwSXm4W/google-sound-library_03ad0264.csv";

export interface SoundEntry {
  category: string;
  sound: string;
  url: string;
}

function normaliseSoundMatchText(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ı/g, "i")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9\s_-]+/g, " ");
}

// ─── Genre → preferred categories ────────────────────────────────────────────

export const GENRE_SOUND_CATEGORIES: Record<string, string[]> = {
  fairy_tale: ["animals", "ambiences", "human_voices", "cartoon", "weather"],
  comic: ["impacts", "cartoon", "crowds", "transportation", "weapons"],
  crime_mystery: ["ambiences", "doors", "foley", "human_sounds", "weather"],
  fantasy_scifi: ["science_fiction", "ambiences", "impacts", "weather"],
  romance: ["ambiences", "human_voices", "animals", "water"],
  horror_thriller: ["horror", "ambiences", "doors", "weather", "impacts"],
};

// Canonical tag -> sound library fragments.
// These tags should stay language-agnostic and are the primary signal for audio matching.
export const SFX_TAG_FRAGMENT_MAP: Record<string, string[]> = {
  wind: ["wind", "breeze", "gust"],
  rain: ["rain", "storm"],
  thunder: ["thunder", "storm"],
  water: ["water", "ocean", "wave", "river"],
  forest: ["forest", "birds", "leaves"],
  birds: ["bird", "birds", "owl"],
  fire: ["fire", "crackle"],
  door: ["door", "creak", "gate"],
  footstep: ["footstep", "step", "run"],
  crowd: ["crowd", "market", "city"],
  city: ["city", "street", "traffic"],
  paper: ["paper", "page", "book"],
  music: ["music", "piano", "guitar"],
  soft: ["soft", "gentle", "calm"],
  quiet: ["quiet", "silence", "whisper"],
  heartbeat: ["heartbeat", "pulse", "heart"],
  horror: ["horror", "haunted", "ghost", "creak"],
  magic: ["magic", "sparkle", "chime", "fairy"],
  chime: ["chime", "bell", "sparkle"],
  star: ["night", "space", "star"],
  moon: ["night", "owl", "cricket"],
  rocket: ["rocket", "launch", "engine", "jet"],
  spaceship: ["space", "ship", "engine", "sci"],
  space: ["space", "sci", "laser", "cosmic"],
  machine: ["machine", "robot", "computer", "mechanical"],
  computer: ["computer", "beep", "digital"],
  alarm: ["alarm", "siren", "alert"],
  static: ["static", "radio", "buzz"],
  radio: ["radio", "static", "broadcast"],
  mystery: ["suspense", "mystery", "tension"],
  suspense: ["suspense", "tense", "heartbeat"],
  impact: ["impact", "hit", "punch", "crash"],
  hero: ["hero", "impact", "whoosh"],
  whoosh: ["whoosh", "swish", "swoosh"],
  train: ["train", "rail", "station"],
  cafe: ["restaurant", "cafe", "indoor"],
  lantern: ["lantern", "chime", "night"],
};

// ─── Keyword → sound name fragments ──────────────────────────────────────────
// Used to match page content to relevant sounds

export const CONTENT_KEYWORD_MAP: Array<{ keywords: string[]; soundFragments: string[] }> = [
  // Nature / outdoor
  { keywords: ["forest", "tree", "woods", "jungle", "orman", "agac"], soundFragments: ["forest", "birds", "wind", "leaves"] },
  { keywords: ["rain", "storm", "thunder", "lightning", "yagmur", "firtina", "gok gurultusu", "simsek"], soundFragments: ["rain", "thunder", "storm"] },
  { keywords: ["ocean", "sea", "wave", "beach", "water", "okyanus", "deniz", "dalga", "su"], soundFragments: ["ocean", "wave", "water", "rain"] },
  { keywords: ["wind", "breeze", "gust", "ruzgar", "esinti"], soundFragments: ["wind", "breeze"] },
  { keywords: ["fire", "flame", "burn", "blaze"], soundFragments: ["fire", "crackle"] },
  { keywords: ["cave", "underground", "dungeon"], soundFragments: ["cave", "drip", "echo"] },
  // Animals
  { keywords: ["horse", "gallop", "ride", "steed"], soundFragments: ["horse", "gallop"] },
  { keywords: ["dog", "wolf", "howl"], soundFragments: ["dog", "wolf", "howl"] },
  { keywords: ["bird", "fly", "wing", "eagle", "owl"], soundFragments: ["bird", "owl", "wing"] },
  { keywords: ["cat", "meow", "purr"], soundFragments: ["cat", "meow"] },
  { keywords: ["dragon", "roar", "beast", "monster"], soundFragments: ["roar", "monster", "growl"] },
  // Human / crowd
  { keywords: ["crowd", "people", "market", "town", "city", "kalabalik", "insanlar", "pazar", "sehir"], soundFragments: ["crowd", "market", "city"] },
  { keywords: ["laugh", "cheer", "celebrate", "gul", "kahkaha", "sevin", "kutla"], soundFragments: ["laugh", "cheer", "crowd"] },
  { keywords: ["scream", "cry", "shout", "yell", "ciglik", "bagir", "agla"], soundFragments: ["scream", "shout"] },
  { keywords: ["whisper", "quiet", "silence", "fisilda", "sessiz", "sessizlik"], soundFragments: ["whisper", "quiet"] },
  // Action / combat
  { keywords: ["fight", "battle", "sword", "attack", "punch", "hit", "kavga", "savas", "kilic", "saldiri", "vur"], soundFragments: ["sword", "punch", "hit", "fight", "battle"] },
  { keywords: ["gun", "shoot", "bullet", "pistol", "rifle"], soundFragments: ["gun", "shot", "bullet"] },
  { keywords: ["explosion", "bomb", "blast", "patlama", "bomba"], soundFragments: ["explosion", "blast"] },
  { keywords: ["run", "chase", "escape", "flee", "kos", "kovala", "kac"], soundFragments: ["run", "footstep"] },
  // Doors / buildings
  { keywords: ["door", "open", "close", "enter", "room", "kapi", "ac", "kapat", "giris", "oda", "gecit"], soundFragments: ["door", "creak"] },
  { keywords: ["stairs", "step", "walk", "footstep", "merdiven", "adim", "yuru"], soundFragments: ["footstep", "step"] },
  { keywords: ["window", "glass", "break", "shatter"], soundFragments: ["glass", "break"] },
  // Transport
  { keywords: ["car", "drive", "road", "highway", "araba", "yol"], soundFragments: ["car", "engine", "road"] },
  { keywords: ["train", "rail", "station"], soundFragments: ["train"] },
  { keywords: ["ship", "boat", "sail", "sea", "gemi", "tekne"], soundFragments: ["ship", "boat"] },
  { keywords: ["plane", "fly", "aircraft", "jet", "ucak", "uc"], soundFragments: ["plane", "jet"] },
  { keywords: ["rocket", "roket", "spaceship", "uzay gemisi", "motor"], soundFragments: ["rocket", "engine", "space", "jet"] },
  // Sci-fi / fantasy
  { keywords: ["space", "planet", "star", "galaxy", "cosmos", "uzay", "gezegen", "yildiz", "galaksi", "evren", "ay"], soundFragments: ["space", "sci", "laser", "night"] },
  { keywords: ["magic", "spell", "enchant", "wizard", "witch", "sihir", "buyu", "buyulu", "masal"], soundFragments: ["magic", "sparkle", "chime"] },
  { keywords: ["robot", "machine", "computer", "tech", "robot", "makine", "bilgisayar", "teknoloji", "harita"], soundFragments: ["robot", "machine", "computer", "beep"] },
  // Horror
  { keywords: ["ghost", "haunted", "spirit", "dark", "shadow"], soundFragments: ["ghost", "haunted", "horror"] },
  { keywords: ["blood", "death", "kill", "murder"], soundFragments: ["horror", "stab", "heartbeat"] },
  { keywords: ["heartbeat", "pulse", "heart"], soundFragments: ["heartbeat"] },
  // Romance / peaceful
  { keywords: ["love", "kiss", "romance", "tender", "gentle", "ask", "opucuk", "romantik", "nazik", "yumusak"], soundFragments: ["piano", "gentle", "soft"] },
  { keywords: ["music", "song", "sing", "dance", "muzik", "sarki", "soyle", "dans", "melodi"], soundFragments: ["music", "piano", "guitar", "chime"] },
  // Children / fairy tale
  { keywords: ["fairy", "magic", "wish", "dream", "wonder", "peri", "dilek", "ruya", "hayal"], soundFragments: ["chime", "sparkle", "fairy", "magic"] },
  { keywords: ["child", "children", "kid", "play", "toy", "cocuk", "oyun", "oyuncak"], soundFragments: ["children", "play", "toy"] },
  { keywords: ["moon", "night", "star", "sleep", "ay", "gece", "uyku"], soundFragments: ["night", "cricket", "owl", "chime"] },
];

/**
 * Given page content and sfxTags, find the best matching sound URL from the library.
 * entries: parsed CSV rows
 */
export function findBestSound(
  entries: SoundEntry[],
  pageContent: string,
  sfxTags: string[],
  genre: string
): string | null {
  if (entries.length === 0) return null;

  const contentLower = normaliseSoundMatchText(pageContent);
  const preferredCategories = (GENRE_SOUND_CATEGORIES[genre] ?? []).map(normaliseSoundMatchText);

  const tagFragments = Array.from(
    new Set(
      sfxTags.flatMap((tag) => {
        const normalizedTag = normaliseSoundMatchText(tag).trim();
        const baseFragments = normalizedTag.split(/[_\s-]+/).filter(Boolean);
        const mappedFragments = SFX_TAG_FRAGMENT_MAP[normalizedTag] ?? [];
        return [...baseFragments, ...mappedFragments].map(normaliseSoundMatchText);
      }).filter(Boolean)
    )
  );

  // Build candidate list from content keywords
  const contentFragments: string[] = [];
  for (const { keywords, soundFragments } of CONTENT_KEYWORD_MAP) {
    if (keywords.some(kw => contentLower.includes(normaliseSoundMatchText(kw)))) {
      contentFragments.push(...soundFragments.map(normaliseSoundMatchText));
    }
  }

  const dedupedContentFragments = Array.from(new Set(contentFragments.filter(Boolean)));

  // Score each entry
  const scored = entries.map(entry => {
    let score = 0;
    const soundLower = normaliseSoundMatchText(entry.sound);
    const catLower = normaliseSoundMatchText(entry.category);

    // Preferred genre category bonus
    if (preferredCategories.includes(catLower)) score += 3;

    // Canonical sfx tags are the primary, language-agnostic signal.
    for (const frag of tagFragments) {
      if (soundLower.includes(frag)) score += 9;
    }

    // Page-content keyword matching is only a weak fallback/tie-breaker.
    for (const frag of dedupedContentFragments) {
      if (soundLower.includes(frag)) score += 2;
    }

    return { entry, score };
  });

  // Sort by score descending, then pick the best
  scored.sort((a, b) => b.score - a.score);

  // Return top match if it has any score, otherwise fall back to genre category
  const best = scored[0];
  if (best && best.score > 0) return best.entry.url;

  // Fallback: pick a random entry from the preferred genre categories
  const fallbacks = entries.filter(e => preferredCategories.includes(e.category));
  if (fallbacks.length > 0) {
    return fallbacks[Math.floor(Math.random() * fallbacks.length)].url;
  }

  return null;
}
